baseurl                  = "https://miki.gallery"
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "lfjlit"
pygmentsStyle            = "monokai"
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "favicon.ico"
    homepage             = "home"
    # footerText           = "miki.gallery"

# Metadata for Open Graph and Twitter
    title                = "lfjlit"
    description          = "Welcome to miki's website"
    images               = ["lfjlit.jpg"]

[[params.mainMenu]]
    link = "/news"
    text = "news"

[[params.mainMenu]]
    link = "/paintings"
    text = "paintings"

[[params.mainMenu]]
    link = "/drawings"
    text = "drawings"

[[params.mainMenu]]
    link = "/about"
    text = "me"

# [[params.words]]
#     text = "I'm miki."
# [[params.words]]
#     text = "I like designing and painting."
# [[params.words]]
#     text = 'But my real goal is to <a class="blue">make</a> <a class="blueb">art</a>.'

[[params.social]]
    url = "https://instagram.com/lfjlit"
    fa_icon = "fab fa-instagram"

[[params.social]]
    url = "https://twitter.com/lfjlit"
    fa_icon = "fab fa-twitter"

[[params.social]]
    url = "mailto:lfjlit@gmail.com"
    fa_icon = "far fa-envelope"

[imaging]
    quality = 75
