baseurl                  = "https://miki.gallery"
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "MIKI's Gallery"
theme                    = "sam"
pygmentsStyle            = "monokai"
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "home"
    footerText           = "miki.gallery"

# Metadata for Open Graph and Twitter
    description          = "Gallery for Miki ISHIYAMA"
    images               = ["tn.png"]
    title                = "MIKI's Gallery"

[[params.mainMenu]]
    link = "/news"
    text = "news"

[[params.mainMenu]]
    link = "/gallery"
    text = "gallery"

[[params.mainMenu]]
    link = "/portfolio"
    text = "portfolio"

[[params.mainMenu]]
    link = "/about"
    text = "who is miki?"

[imaging]
    quality = 75
