baseurl                  = "https://miki.gallery"
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "MIKI's Gallery"
theme                    = "sam"
pygmentsStyle            = "monokai"
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "home"
    # footerText           = "miki.gallery"

# Metadata for Open Graph and Twitter
    title                = "MIKI's Gallery"
    description          = "Gallery for Miki"
    images               = ["tn.png"]

[[params.mainMenu]]
    link = "/news"
    text = "news"

[[params.mainMenu]]
    link = "/gallery"
    text = "gallery"

[[params.mainMenu]]
    link = "/portfolio"
    text = "portfolio"

[[params.mainMenu]]
    link = "/about"
    text = "contact"

[[params.social]]
    url = "https://instagram.com/lfjlit"
    fa_icon = "fa-instagram"

[[params.social]]
    url = "https://twitter.com/lfjlit"
    fa_icon = "fa-twitter"

[imaging]
    quality = 75
