backend:
  name: git-gateway
  branch: master

media_folder: "/static/images"
public_folder: "/images/"

publish_mode: editorial_workflow

collections:
  - label: "News"
    name: "news"
    folder: "content/news"
    create: true
    # slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    slug: "{{slug}}"
    preview_path: "news/{{slug}}"
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "公開日", name: "date", widget: "datetime", dateFormat: "YYYY-MM-DD"}
      - {label: "公開日を表示する", name: "showDate", widget: "boolean", default: true}
      - {label: "タグ", name: "tags", widget: "list", required: false}
      - {label: "本文", name: "body", widget: "markdown"}
  - label: "Pages"
    name: "pages"
    create: true
    delete: false
    files:
      - label: "About Page"
        name: "about"
        file: "content/about.md"
        fields:
          - {label: "タイトル", name: "title", widget: "string"}
          - {label: "公開日", name: "date", widget: "datetime", dateFormat: "YYYY-MM-DD"}
