backend:
  name: git-gateway
  branch: master

media_folder: "static/images"

public_folder: "images/"

collections:
  - label: "Blog"
    name: "news"
    folder: "content/news"
    create: true
    # slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    slug: "{{slug}}"
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "公開日", name: "date", widget: "datetime", dateFormat: "YYYY-MM-DD"}
      - {label: "公開日を表示する", name: "showDate", widget: "boolean", default: true}
      - {label: "本文", name: "body", widget: "markdown"}
      - {label: "タグ", name: "tags", widget: "list", required: false}
      # - {label: "サムネイル画像", name: "thumbnail", widget: "image"}
